# Generated by Django 5.1.2 on 2024-10-13 00:02

from django.db import migrations, models
from django.db.models import F
from django.utils import timezone


def set_initial_recap_numbers(apps, schema_editor):
    Deal = apps.get_model('deals', 'Deal')
    deals = Deal.objects.all().order_by('created_at')
    
    current_month = None
    current_number = 0

    for deal in deals:
        deal_month = deal.created_at.replace(day=1)
        if deal_month != current_month:
            current_month = deal_month
            current_number = 0
        
        current_number += 1
        deal.recap_number = current_number
        deal.save()


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='recap_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RunPython(set_initial_recap_numbers),
    ]