# Generated by Django 5.1.2 on 2024-10-13 07:19

import django.utils.timezone
from django.db import migrations, models
from django.utils import timezone
from django.db.models import F


def set_initial_recap_numbers(apps, schema_editor):
    Deal = apps.get_model('deals', 'Deal')
    deals = Deal.objects.all().order_by('created_at')
    
    current_month = None
    current_new_number = 0
    current_used_number = 0

    for deal in deals:
        deal_month = deal.created_at.replace(day=1)
        if deal_month != current_month:
            current_month = deal_month
            current_new_number = 0
            current_used_number = 0
        
        if deal.car_type == 'NEW':
            current_new_number += 1
            deal.recap_number = current_new_number
        else:
            current_used_number += 1
            deal.recap_number = current_used_number
        deal.save()



class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0003_alter_deal_options_deal_car_type_deal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='car_type',
            field=models.CharField(choices=[('NEW', 'New Car'), ('USED', 'Used Car')], default='USED', max_length=4),
        ),
        migrations.AddField(
            model_name='deal',
            name='recap_number',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RunPython(set_initial_recap_numbers),
    ]