# Generated by Django 5.1.2 on 2024-10-13 07:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0004_deal_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='date',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
