# Generated by Django 5.1.2 on 2024-10-13 07:28

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0005_deal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
