# Generated by Django 5.1.2 on 2024-10-13 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0006_alter_deal_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deal',
            name='recap_number',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
