# Generated by Django 5.1.2 on 2024-10-13 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deals', '0007_alter_deal_recap_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='vehicle_make',
        ),
        migrations.AlterField(
            model_name='deal',
            name='vehicle_model',
            field=models.CharField(max_length=80),
        ),
    ]
